Apps doc updates
ivoa/ivoa-web pull request #21
Opened 2024-05-21 04:24 UTC by andamian

2024-05-21 04:28 UTC, andamian commented
@molinaro-m - this looks better. Thanks for the tip.

2024-05-21 04:28 UTC, molinaro-m approved these changes
Perfect! Now it works, both locally and on the webtest preview branch

2024-05-21 04:29 UTC, molinaro-m commented
> @molinaro-m - this looks better. Thanks for the tip.

it's more like what we will operate tomorrow.
I think the fork+PR will need to be the forward mechanism when this goes production.

2024-05-21 06:38 UTC, JeremyMcCormick requested changes
Conflict on `content/_index.html` needs to be fixed. There was a big update to the site style that you probably don't have integrated into your branch.

Second, more minor issue, and not to be too picky about Git stuff since we haven't broadcasted this widely yet, but `apps` is not a very good branch name. What we are preferring is making an issue in the tracker first, then using it in the name like `iss1234` or `iss1234-port-apps`. I won't block the PR based on this (just the conflict needs to be fixed), but please in the future make an issue first and then name your branch after it.

2024-05-21 06:42 UTC, gmantele commented
This conflict is because of my last commit. All the links are now in a different file: `layout/partials/sitemap.html`. This way, it can be put at the bottom of all pages.

2024-05-21 06:44 UTC, JeremyMcCormick commented on content/pages/astronomers/applications.md
> +date: 2024-02-09T10:00:00+02:00
The `date` can be left out - this is not correct anyways and Hugo will insert it automatically.

2024-05-21 06:48 UTC, gmantele commented
I can, indeed. I will probably wait for the PR #23 to be merged first, as it touches as well the `sitemap.html` file in the way it is done in this PR.

2024-05-21 06:48 UTC, gmantele commented
By the way, should this PR stay a Draft?

2024-05-21 06:51 UTC, andamian commented
@gmantele and @JeremyMcCormick - thanks for the feedback. This is a draft PR that I've started in preparation for the hackathon. I can probably solve the conflict at the end when the PR is ready which right now is not.

2024-05-21 06:53 UTC, JeremyMcCormick commented
> @gmantele and @JeremyMcCormick - thanks for the feedback. This is a draft PR that I've started in preparation for the hackathon. I can probably solve the conflict at the end when the PR is ready which right now is not. The page Apps page has not been worked on.

Understood, we can look at this tomorrow then. 👍

2024-05-21 06:58 UTC, andamian commented
@JeremyMcCormick - I'm probably jumping the gun here without having clear directions on how we are going to proceed. I just assume that in this PR we will fix all the issues raised in https://docs.google.com/spreadsheets/d/15TE9LCNdDyBhAQF_TyX2AqXSXW8RxQqHkU_bBKxQK7I/edit#gid=0. I will adapt later if that's not the case.

2024-05-22 01:34 UTC, JeremyMcCormick commented
> @JeremyMcCormick - I'm probably jumping the gun here without having clear directions on how we are going to proceed. I just assumed that in this PR we will fix all the issues raised in https://docs.google.com/spreadsheets/d/15TE9LCNdDyBhAQF_TyX2AqXSXW8RxQqHkU_bBKxQK7I/edit#gid=0. I will adapt later if that's not the case.

Yes, we are hoping to fix at least some of those issues.

Please read the contribution guide:

https://github.com/ivoa/ivoa-web/blob/main/CONTRIBUTING.md

It may clear some things for you in terms of expeceted developer workflow.

2024-05-22 01:38 UTC, gmantele commented
Now that the main conflicting changes are done, maybe we should try to fix the conflict in this branch so that the editing team can work with no problem this afternoon.

2024-05-22 02:08 UTC, JeremyMcCormick commented
> Now that the main conflicting changes are done, maybe we should try to fix the conflict in this branch so that the editing team can work with no problem this afternoon.

Can we put this on a branch that references an issue in the tracker and then reopen a new PR?

I don't want to get in the habit of accepting vague branch names like this, as it is an organizational mess. The issue page also provides a nice place for discussion on the issue.

@andamian You can just branch from your existing one like `git checkout apps && git checkout -b iss1234` which will keep your work.

2024-05-22 02:21 UTC, andamian commented
Replaced with #26

2024-05-22 02:21 UTC, closed without merging